services:
  app:
    build: .
    command: gunicorn app.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --timeout 120
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
