"""cascading added

Revision ID: 0e3fcb27f45c
Revises: 64009cb4b4be
Create Date: 2025-07-03 03:02:21.782425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e3fcb27f45c'
down_revision: Union[str, None] = '64009cb4b4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verification_tokens', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('email_verification_tokens_user_id_fkey'), 'email_verification_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'email_verification_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('images', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('images_owner_id_fkey'), 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('password_reset_tokens', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('password_reset_tokens_user_id_fkey'), 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('pending_registrations', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.drop_column('pending_registrations', 'is_deleted')
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('password_reset_tokens_user_id_fkey'), 'password_reset_tokens', 'users', ['user_id'], ['id'])
    op.drop_column('password_reset_tokens', 'is_deleted')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key(op.f('images_owner_id_fkey'), 'images', 'users', ['owner_id'], ['id'])
    op.drop_column('images', 'is_deleted')
    op.drop_constraint(None, 'email_verification_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('email_verification_tokens_user_id_fkey'), 'email_verification_tokens', 'users', ['user_id'], ['id'])
    op.drop_column('email_verification_tokens', 'is_deleted')
    # ### end Alembic commands ###
