"""add gender, age, weight, height to user and pending_registration

Revision ID: 2afaf4686d43
Revises: a7b13d9b5e13
Create Date: 2025-07-11 02:06:08.048228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2afaf4686d43'
down_revision: Union[str, None] = 'a7b13d9b5e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_registrations', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('pending_registrations', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('pending_registrations', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('pending_registrations', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'height')
    op.drop_column('users', 'weight')
    op.drop_column('users', 'age')
    op.drop_column('users', 'gender')
    op.drop_column('pending_registrations', 'height')
    op.drop_column('pending_registrations', 'weight')
    op.drop_column('pending_registrations', 'age')
    op.drop_column('pending_registrations', 'gender')
    # ### end Alembic commands ###
