"""update_user_calories_structure

Revision ID: 422386675f13
Revises: 1e5c3e86a365
Create Date: 2025-07-13 01:13:52.688816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '422386675f13'
down_revision: Union[str, None] = '1e5c3e86a365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new calories_burned column as JSON
    op.add_column('user_calories', sa.Column('calories_burned', sa.JSON(), nullable=True))
    
    # Copy data from old column to new column (convert integer to JSON array format)
    op.execute("""
        UPDATE user_calories 
        SET calories_burned = json_build_array(
            json_build_object('activity_name', 'general', 'calories', calories_burn::text)
        )
        WHERE calories_burn IS NOT NULL
    """)
    
    # Make calories_burned NOT NULL after data migration
    op.alter_column('user_calories', 'calories_burned', nullable=False)
    
    # Drop the old calories_burn column
    op.drop_column('user_calories', 'calories_burn')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add back the old calories_burn column
    op.add_column('user_calories', sa.Column('calories_burn', sa.Integer(), nullable=True))
    
    # Convert JSON data back to integer (sum all calories from activities)
    op.execute("""
        UPDATE user_calories 
        SET calories_burn = (
            SELECT COALESCE(SUM(CAST(activity->>'calories' AS INTEGER)), 0)
            FROM json_array_elements(calories_burned) AS activity
        )
        WHERE calories_burned IS NOT NULL
    """)
    
    # Make calories_burn NOT NULL after data migration
    op.alter_column('user_calories', 'calories_burn', nullable=False)
    
    # Drop the new calories_burned column
    op.drop_column('user_calories', 'calories_burned')
    
    # ### end Alembic commands ###
