"""Add ondelete cascade to user_calories.user_id

Revision ID: 4bb2545eabf1
Revises: faedf006a001
Create Date: 2025-07-16 02:38:03.763906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb2545eabf1'
down_revision: Union[str, None] = 'faedf006a001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_activity_date', 'user_calories', ['activity_date'])
    op.drop_constraint(op.f('user_calories_user_id_fkey'), 'user_calories', type_='foreignkey')
    op.create_foreign_key(None, 'user_calories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_calories', type_='foreignkey')
    op.create_foreign_key(op.f('user_calories_user_id_fkey'), 'user_calories', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_user_activity_date', 'user_calories', type_='unique')
    # ### end Alembic commands ###
