"""add is_meal to image

Revision ID: 64009cb4b4be
Revises: c9e79f94f635
Create Date: 2025-07-03 01:31:43.808103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64009cb4b4be'
down_revision: Union[str, None] = 'c9e79f94f635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('is_meal', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'is_meal')
    # ### end Alembic commands ###
