"""add goal_weight to user and pending_registration

Revision ID: c0f474573279
Revises: 2afaf4686d43
Create Date: 2025-07-11 12:56:30.354455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0f474573279'
down_revision: Union[str, None] = '2afaf4686d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_registrations', sa.Column('goal_weight', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('goal_weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'goal_weight')
    op.drop_column('pending_registrations', 'goal_weight')
    # ### end Alembic commands ###
