"""presigned url

Revision ID: c9e79f94f635
Revises: 3e76bbbf92b2
Create Date: 2025-07-02 19:05:23.219420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e79f94f635'
down_revision: Union[str, None] = '3e76bbbf92b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('presigned_url', sa.String(length=1000), nullable=True))
    op.add_column('images', sa.Column('presigned_url_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'presigned_url_expires_at')
    op.drop_column('images', 'presigned_url')
    # ### end Alembic commands ###
