"""Remove is_deleted columns from all tables

Revision ID: f230882ba0b3
Revises: 1b5fc31154ac
Create Date: 2025-07-03 16:18:21.703861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f230882ba0b3'
down_revision: Union[str, None] = '1b5fc31154ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_verification_tokens', 'is_deleted')
    op.drop_column('images', 'is_deleted')
    op.drop_column('password_reset_tokens', 'is_deleted')
    op.drop_column('pending_registrations', 'is_deleted')
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('pending_registrations', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('password_reset_tokens', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('email_verification_tokens', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
